// Generated by gencpp from file jetson_camera/ImagePair.msg
// DO NOT EDIT!


#ifndef JETSON_CAMERA_MESSAGE_IMAGEPAIR_H
#define JETSON_CAMERA_MESSAGE_IMAGEPAIR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>

namespace jetson_camera
{
template <class ContainerAllocator>
struct ImagePair_
{
  typedef ImagePair_<ContainerAllocator> Type;

  ImagePair_()
    : raw_image()
    , undistorted_image()  {
    }
  ImagePair_(const ContainerAllocator& _alloc)
    : raw_image(_alloc)
    , undistorted_image(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _raw_image_type;
  _raw_image_type raw_image;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _undistorted_image_type;
  _undistorted_image_type undistorted_image;





  typedef boost::shared_ptr< ::jetson_camera::ImagePair_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetson_camera::ImagePair_<ContainerAllocator> const> ConstPtr;

}; // struct ImagePair_

typedef ::jetson_camera::ImagePair_<std::allocator<void> > ImagePair;

typedef boost::shared_ptr< ::jetson_camera::ImagePair > ImagePairPtr;
typedef boost::shared_ptr< ::jetson_camera::ImagePair const> ImagePairConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetson_camera::ImagePair_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetson_camera::ImagePair_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetson_camera::ImagePair_<ContainerAllocator1> & lhs, const ::jetson_camera::ImagePair_<ContainerAllocator2> & rhs)
{
  return lhs.raw_image == rhs.raw_image &&
    lhs.undistorted_image == rhs.undistorted_image;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetson_camera::ImagePair_<ContainerAllocator1> & lhs, const ::jetson_camera::ImagePair_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetson_camera

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetson_camera::ImagePair_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetson_camera::ImagePair_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetson_camera::ImagePair_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetson_camera::ImagePair_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetson_camera::ImagePair_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetson_camera::ImagePair_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetson_camera::ImagePair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a33fecb434ee086eec652837d76184f0";
  }

  static const char* value(const ::jetson_camera::ImagePair_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa33fecb434ee086eULL;
  static const uint64_t static_value2 = 0xec652837d76184f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::jetson_camera::ImagePair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetson_camera/ImagePair";
  }

  static const char* value(const ::jetson_camera::ImagePair_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetson_camera::ImagePair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image raw_image\n"
"sensor_msgs/Image undistorted_image\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::jetson_camera::ImagePair_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetson_camera::ImagePair_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.raw_image);
      stream.next(m.undistorted_image);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImagePair_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetson_camera::ImagePair_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetson_camera::ImagePair_<ContainerAllocator>& v)
  {
    s << indent << "raw_image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.raw_image);
    s << indent << "undistorted_image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.undistorted_image);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETSON_CAMERA_MESSAGE_IMAGEPAIR_H
